version: "3"
services:
  school:
    image: appointmentguru/school:latest
    volumes:
      - ~/.ssh:/root/.ssh # map ssh keys
    command: ansible-playbook /code/ansible/deploy.drf.yml  -i /etc/ansible/inventory/digital_ocean.py -e "organization=appointmentguru service=multiguru entity_name=multi"
    environment:
      - ANSIBLE_HOST_KEY_CHECKING=False
      - ANSIBLE_LIBRARY=/etc/ansible/library