version: "3"
services:
  db:
    image: postgres:9.5
  web:
    build: .
    command: sh /code/test.sh
    depends_on:
      - db
    volumes:
      - .:/code
    environment:
      - CODACY_PROJECT_TOKEN=fed36eaebbc24f1381d65ff7984a9837
