docker_environment:
  - key: DEBUG
    value: False
  - key: DATABASE_NAME
    value: "{{organization}}_{{service}}"
  - key: DATABASE_USER
    value: "{{organization}}_{{service}}"
  - key: DATABASE_PASSWORD
    value: "{{postgres_passwords[service]}}"
  - key: DATABASE_HOST
    value: "{{postgres_db_host}}"
  - key: ALLOWED_HOSTS
    value: "{{docker_service}},{{service}}.{{canonical_tld}}"
  - key: AWS_STORAGE_BUCKET_NAME
    value: media-appointmentguru
  - key: AWS_ACCESS_KEY_ID
    value: "{{aws_access_key}}"
  - key: AWS_SECRET_ACCESS_KEY
    value: "{{aws_secret_key}}"
  - key: KONG_PROVISION_KEY
    value: "{{kong_provision_key}}"
  - key: KONG_CLIENT_ID
    value: "{{kong_client_id}}"
  - key: KONG_CLIENT_SECRET
    value: "{{kong_client_secret}}"
  - key: KONG_OAUTH_BASE_URL
    value: "{{kong_oauth_base_url}}"
  - key: KONG_PROVISION_KEY
    value: "{{kong_provision_key}}"