# Generated by Django 2.0.2 on 2018-02-17 13:00

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owners', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=36), default=[], size=None)),
                ('members', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=36), default=[], size=None)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('can_view_slots', 'Can view available slots in your calendar'), ('can_view_calendar', 'Can view your calendar'), ('can_create_appointment', 'Can create appointments on your calendar'), ('full_access', 'Full access to your account')], max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Group')),
            ],
        ),
    ]
