# Generated by Django 2.0.2 on 2018-05-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_hub'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='hero_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hub',
            name='is_password_protected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hub',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hub',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='hub',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
