# Generated by Django 2.0.2 on 2018-05-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180511_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='theme_color',
            field=models.CharField(default='orange', max_length=255),
        ),
    ]
